Vagrant.configure("2") do |config|

    config.vm.box = "precise64"
	config.vm.box_url = "http://files.vagrantup.com/precise64.box"
	config.vm.network :forwarded_port, guest: 15672, host: 15672
    
	config.vm.provision :shell, :path => "rabbitmq.sh"

end