Vagrant.configure("2") do |config|

    config.vm.box = "precise64"
	config.vm.box_url = "http://files.vagrantup.com/precise64.box"
	config.vm.network :forwarded_port, guest: 6379, host: 6379, auto_correct: true
    
	config.vm.provider :virtualbox do |vb|
		vb.customize ["modifyvm", :id,"--memory", "512"]
		vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
	end
  
	config.vm.provision :shell, :path => "init.sh"

end
